:concurrency: 5
:queues:
  - default
:scheduler:
  :schedule:
    weekly_report_job:
      # cron: "* * * * *" #runs every minute
      cron: "0 0 * * 0" #run every week at sunday
      class: "WeeklyReportJob"
